### ISSUE TITLE
[Query]Can a Play button be provided at this place?

### ISSUE THREAD

**Issue by onlytanmoy** [marduklev/skin.swan-alpha#13]
Hi mate, hope you doing well.
I am using the latest update of the skin. 
Please see the screenshot
![Kodi_20220123_100156](https://user-images.githubusercontent.com/48493659/150673514-2754cc88-67d3-4eba-ae4c-14b358ca3778.png)
I was wondering if it will be possible to include a 'Play' button here adjacent to Plot button?

**Comment by marduklev** [comment]
It is already in, if item is in lib.
unsure how to resolve it playng via / from video addon...

![Imgur Image](https://i.imgur.com/aWktTXy.png)

**Comment by onlytanmoy** [comment]
Ah...I see...I actually don't do local files just play via one of the video-addons, so that's why it is missing in my case.
It will be great if you can look into the possibility of adding one for future :)

On another note please see the screen record: https://streamable.com/3bv2tg
The empty gap between Actors and Crew can that be removed? If it is easier to chat then let me know your reddit or discord username to message.

**Comment by marduklev** [comment]
That's alreaydy possible

- settings - > skinsettings -> Library Section - on right side navigate to ''Select Which Container To Hide in VideoInfo"
https://streamable.com/ba7gl4

Im closing this,  'addon playback' for legit stuff is on to do (tmdb api, jurialmunkey plugin)
