### ISSUE TITLE
dependency on script.swan.helper version 0.0.02 could not be satisfied

### ISSUE THREAD

**Issue by meesterexx** [marduklev/skin.swan-alpha#15]
Just tried updating from latest master and got dependency error:
CAddonInstallJob[skin.swan]: The dependency on script.swan.helper version 0.0.02 could not be satisfied.

Updates from latest master in past have always been fine. Did I do something wrong?

**Comment by meesterexx** [comment]
I just tried to install script.swan.helper from your git, but that didn't work either as it's still at .01 according to it's addon.xml

**Comment by marduklev** [comment]
it is in progress.i learn some py and may replace some functions .
try this for the moment till i am done

https://github.com/marduklev/repository.marduk/raw/master/matrix/script.swan.helper/script.swan.helper-0.0.02.zip

**Comment by meesterexx** [comment]
I grabbed the .03 from your git and that worked. Thanks!
