### ISSUE TITLE
[Bug] Special Paths from File manager don't show in the Browse for folder or image area.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [marduklev/skin.swan-alpha#16]
Hi, I really love this skin but its hard to customize but I love how this skin is made and all. Only problem im having is customization because the file manager sources are not showing in the custom paths. Its kinda confusing to understand but here are some images of what i mean.

## Images that are part of the bug
- Browse for image does not have my media sources added
![image](https://user-images.githubusercontent.com/62456796/170866122-d5cb3f28-e06f-4c45-b593-e44f62e3ffa9.png)
- File Manager with media sources added
![image](https://user-images.githubusercontent.com/62456796/170865569-3ff09fd2-ada0-42c2-ae0e-20d8d9baf16d.png)

## A Different skin of how it should be displayed
- Browse for image does have my media sources added
![Browse for image](https://user-images.githubusercontent.com/62456796/170866093-8184b1cf-8a5c-4276-a656-2c54b2c3b711.png)
-  File Manager with media sources added
![File Manager](https://user-images.githubusercontent.com/62456796/170866106-516c1623-605e-4340-8e6f-ba1aab8ebb81.png)

Media sources are just not showing in the file browser and reason why i need this is so i can add my special paths and network smb locations and so i can set my build for other devices.

**Comment by marduklev** [comment]
Its not really a skin related issue, more a "limitation" of kodi core function.

The Filebrowser (used for set custom skin paths for images via skin.setimage() and the filemanager are 2 different windows.

What you can do is the following, as the skin allows to ' nominate ' a user folder for image lookups.

Go to setting -> skinsettings -> background section > on the right you'll see as second entry "Choose your folderpath if you like to use own source folders..."

- there you can set up a path where the skin will start looking at whenever the skin provide a function to set specific images
