### ISSUE TITLE
[Question or Bug] Weather icons are offset, is this a bug or do you need a specific icon pack.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [marduklev/skin.swan-alpha#17]
Hi sorry for bothering you but Weather Icons are offset and im not sure if this is a bug or i need a specific weather icon pack for this skin. If you can tell me if this is a bug or how to install a specific weather icon pack, that would be appreciated. 

Thank you and btw, You nailed the ratings then any other skin i used so huge thank you for making this skin.

# Weather
![Weather](https://user-images.githubusercontent.com/62456796/170866875-4ff44fd7-cd4b-4be6-abb7-9832849bccda.png)

**Comment by Goldenfreddy0703** [comment]
Actually i see that you have an option that says "Get The Daylie Icon Centered" so its probably supposed to look like that.

**Comment by marduklev** [comment]
That is actually intended.

BUT ;-) there are some options, available via menupanel

- hit menu/or click left till the menu bar slides out
- you'll see an icon bar, which offers options depending which icon has focus, in that case the 2nd icon from left offers some more options 
  https://i.imgur.com/1acik4n.png
