### ISSUE TITLE
[Very Small Low Priorty Bug] Skins Settings > Currently Playing (Thats about it)

### ISSUE THREAD

**Issue by Goldenfreddy0703** [marduklev/skin.swan-alpha#18]
![image](https://user-images.githubusercontent.com/62456796/170867393-b71445c7-25b9-4755-9488-338fca5c9086.png)
There's really no explaining to this one. 😂

**Comment by marduklev** [comment]
That's just a placeholder, which remind me that i wanted to some layouts there.
The setting buttons dont change anything (currently)
