### ISSUE TITLE
Kodi 19 Home Widgets directed to Tv shows in a video addon does nothing

### ISSUE THREAD

**Issue by SoreTissue** [marduklev/skin.swan-alpha#2]
Thanks for a beautiful skin. I know you've stated this hasn't really been tested in Kodi 19 but I thought this may be a bug you wasn't aware of and maybe easy to fix some day down the track. 

Kodi 19 RC1 64 bit 
Windows 10

When using home widgets, if you set path to a video addon tv show list, nothing happens when you click on a show. The Tv Show list displays fine as a widget, you can choose information and then select play to get to seasons/episodes that way, but if you just click on the show's poster it simply does nothing. You can hear the click from selecting show but nothing happens. 

Nothing in Log file.

**Comment by marduklev** [comment]
@SoreTissue 

this should fix it, can you report back ?!

https://github.com/marduklev/skin.swan-alpha/commit/604969210db7305327054a4cd8be499373de1d09

**Comment by SoreTissue** [comment]
Fixed. Tested a couple of video addons and they are now working.

**Comment by marduklev** [comment]
> Fixed. Tested a couple of video addons and they are now working.

great.thx for report.
did't noticed it.

**Comment by marduklev** [comment]
solved
