### ISSUE TITLE
TMDB rating value not showing in info panel views 510-512

### ISSUE THREAD

**Issue by meesterexx** [marduklev/skin.swan-alpha#20]
The TMDB rating value is not showing under the TMDB logo in info panel views, but it shows in other views. In the example below I was in the spotlight view first, so I know it had the value for the rating before changing to the info panel view. It does this in all 3 info panel views. Using latest master from github this morning.

![screenshot00000](https://user-images.githubusercontent.com/13154733/183983910-204db5cd-4f28-43a6-92c0-330dc39b6f57.png)

![screenshot00001](https://user-images.githubusercontent.com/13154733/183983942-749c2215-d92a-42ec-b34d-66591ed41f44.png)

**Comment by marduklev** [comment]
I still got something to do how i handle this

- the current issue is that i rely on 3 steps
 - default rating | embuary helper (showing scraped ratings) | optional TMDB helper as fallback

(currently there is more than one naming conventions for tmdb ratings , which may cause double items for tmdb flags n ratings IF fallback via TMDB helper is enabled )

https://forum.kodi.tv/showthread.php?tid=369257

**Comment by meesterexx** [comment]
Thank you. FYI, I do get the double TMDB logo if TMDB is enabled as fallback. I get nothing but the single red star rating if it's disabled. Not a problem, I know it's on your radar for future.

![image](https://user-images.githubusercontent.com/13154733/184645470-bfe1e9a0-28ec-4f20-a3b2-ab7063ade621.png)
