### ISSUE TITLE
Feature request - Would it be possible to add episodes to view lock options on infopanel landscape (512)?

### ISSUE THREAD

**Issue by meesterexx** [marduklev/skin.swan-alpha#21]
I think it looks nice and I'm using infopanel views elsewhere, but it's not available in the lock view options. I additionally tried setting it through both the 3rd party addon I'm testing and through directly editing the settings.xml 
`<setting id="view_locked_episodes" type="string">512</setting>`  but it doesn't work.

Also, would it be possible to add the air date of the episode like it is in vertical infolist (56) rather than just the year? Thank you!

![screenshot00002](https://user-images.githubusercontent.com/13154733/183988804-cc85fec7-e48f-4eb4-a9f1-923ee78b236b.png)

![screenshot00003](https://user-images.githubusercontent.com/13154733/183988845-cb691ce2-8b83-40a0-b933-b7f2b31fcb48.png)

**Comment by marduklev** [comment]
done ;-)

- i think i left over some things for that kind of views anyway, if you found something just ask again ;)

**Comment by meesterexx** [comment]
Thank you, working here. 
If you get some time in the future, could you add the air date of the episode instead of just the year?
Thanks again.
