### ISSUE TITLE
Need Submenu

### ISSUE THREAD

**Issue by Tredap** [marduklev/skin.swan-alpha#22]
Is it possible to make sub menus for each Title on the Home Screen - Want to add an extra menu under the main menus at the front or home screen. Also, how to set the Home Screen layout like the Bingie Mod home screen like the Netflix style home screen, I don't know or maybe I'm missing something. Okay, thank you for a wonderful skin, it's beautiful.

**Comment by marduklev** [comment]
hi, sorry for long delay.
struggle with time and motivation to work on here.
But i will update from time to time.

submenus are hardcoded but can be enabled.
there is no plan for customize the submenu, if a main menu entry has subsections by default (e.g. movies as root) a submenu will be available.
It should also be possible when using custom nodes -> https://kodi.wiki/view/Video_nodes#Manually_creating_or_editing_a_custom_parent_node

The netflix style layout is called 'spotlight' , can be choosen in skinsettings -> Home Layout -> on top right you can choose between 3 layouts.
