### ISSUE TITLE
Video information 

### ISSUE THREAD

**Issue by trkselim** [marduklev/skin.swan-alpha#3]
Thanks for a beautiful skin

When i select movie or tv information form video addon there in no cast&similar only soundtrack

**Comment by marduklev** [comment]
Unsure, may Cast isnt Provided by some addons, i will take a look later...

**Comment by marduklev** [comment]
Ok, i added the default container as workaround.
Cast Content will shown, Actor Thumbs will be missing (if not provided by addon)
https://github.com/marduklev/skin.swan-alpha/commit/9f9e628c8bb68b4b471b9ce05bbf08771b0f0a58
