### ISSUE TITLE
[Feature Request]Add to Trakt list option for movies/shows

### ISSUE THREAD

**Issue by onlytanmoy** [marduklev/skin.swan-alpha#6]
Hiya, first things first, this is a brilliant skin, so thank you for that.

Please watch the screen record from my Kodi 19 running on Shield using your skin
https://imgur.com/a/6K0ZPjw

When I browse for movies of a particular actor and click on one (in my example The Witches of Anne Hathaway) can you include 'Add to Trakt watch-list or custom lists' in the panel where we have Plot, Close and Previous as a + Icon or Trakt icon etc?
As you might know tmdbhelper provides trakt management functions: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Trakt-Management-Functions
Can you please try to implement that? At the moment this feels the only feature absent in this beautiful skin.

**Comment by marduklev** [comment]
I'll take a look.
at least, cast items should work actually.

**Comment by onlytanmoy** [comment]
@marduklev yes please, that will be great, thank you.

**Comment by marduklev** [comment]
> 
> 
> @marduklev yes please, that will be great, thank you.

Did first steps for videoinfo dialog, and can be tested...

BUT there is an issue in matrix (plugin related related), there you'll still have to use the context menu

https://github.com/marduklev/skin.swan-alpha/commit/129c81d9532bfdc8ce2c3129e240132e3c29900d

**Comment by marduklev** [comment]
- trakt manage from videoinfo shoukd work now, kodi version shoul'nt matter
( leia will work if using current themoviedb.helper version provided by kodi repo v2.x.xx

- i m a bit busy right now so, implement it to embuaryinfo dialog will take a bit time.

may test latest changes and report back if sonething go wrong on your end

**Comment by marduklev** [comment]
it should be at the button bar on top.
https://streamable.com/fzus4x

**Comment by onlytanmoy** [comment]
Got the new update of the skin now and its working fine there :)
Thanks for your screen record mate. Closing this ticket.

**Comment by marduklev** [comment]
tough..i found one mistake on my end..

**Comment by marduklev** [comment]
now it will also use the correct current id if not exist before ( e.g. open dialog via title fallbacks )

https://github.com/marduklev/skin.swan-alpha/commit/613f4daf2ad07f329ebfe98454d3270687a05ff8
