### ISSUE TITLE
Possible requests

### ISSUE THREAD

**Issue by deyooluv** [marduklev/skin.swan-alpha#8]
please I have a few requests
1. I am wondering if you will be adding playlist button in the video OSD
2. Tmdb helper have service monitor. Will you be adding rating from add-on. I know rating only works in scraped library items.
3. Will it be possible to create a workaround to play media from  embruary info since you are using it for cast & more.

By the way you have an amazing skin. Thank you

**Comment by marduklev** [comment]
I take a look

1. yepp, i will do, unsure when, also other stuff is missing, especially bookmarks...
2. will take a look soon, if easy task i'll be in in next update
3. will see when i found time, but i think it's handled internally by the script, means the onclick action is proposed to open script-embuary-video.xml and just than you can playback the video....maybe need a request in embuaryinfo forum/git hub branch

**Comment by marduklev** [comment]
to point 2.

may report back , as pretty much untested.
Trakt rating is on to do for later state

https://github.com/marduklev/skin.swan-alpha/commit/38f7c6390e54e0523a73b2cecef279b036d94dba

**Comment by deyooluv** [comment]
> to point 2.
> 
> may report back , as pretty much untested.
> Trakt rating is on to do for later state
> 
> [38f7c63](https://github.com/marduklev/skin.swan-alpha/commit/38f7c6390e54e0523a73b2cecef279b036d94dba)

I appreciate for taking out of your busy time to reply my request.  I directly browse through add-on rather than play media through library items. 

Browsing through add-on and using the spotlight poster view I have noticed items(shows or movies) don't load fast.  List view seems to be the only view that loads items fast when browsing through add-ons.
 I can open a new issue about this if you want.
Thanks again

**Comment by deyooluv** [comment]
@marduklev the fallback for online rating works fine after testing. However rating is missing on the home screen.

**Comment by deyooluv** [comment]
@marduklev The fallback for online rating works fine after testing. However the rating takes 5-8 seconds to show up and also rating is missing on the home screen(spotlight)

**Comment by deyooluv** [comment]
> @deyooluv To Point 1 Did some changes in git version, related to playlist functionalyty. Either Playlist has more than 1 item or Episode is Playling (local Library) https://streamable.com/vxv4ys
> 
> Layout is not really done, but do its job ;-)
> 
> For Point 3, i'll take a look soon too. But no Promise at the DialogOpen is default Action, and Override Actions cant be used in Default Media Containers/Views

@marduklev I appreciate your time in making the skin better. the playlist button in the video OSD is nice. For point 3 another skin called (arctic zephyr reloaded) did a workaround using tmdb helper I believe to play video from embuary info. Maybe this can help you implement point 3.
Thanks again

**Comment by marduklev** [comment]
hm.. i revisit and did some checks.
Play is just possible within the embuary info dialog and if item is part of library.
So there is nothing i can do atm...may there are some possibility in 'themoviedb.helper' plugin...
i'll see.

But closed this for now ;-/
